version: '3.9'

services:
  #  backend:
  #    build:
  #      context: ./backend
  #      dockerfile: Dockerfile
  #
  #    env_file:
  #      - .env
  #    working_dir: /app
  #    volumes:
  #      - "./backend:/app"
  #
  #    ports:
  #      - "${BACKEND_PORT:-7001}:${BACKEND_PORT:-7001}"
  #
  #    command: poetry run uvicorn main:app --host 0.0.0.0 --port ${BACKEND_PORT:-7001}

  frontend:
    container_name: "ten-manage-frontend-container"
    image: "ten-manage-frontend-image"
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile.local
    working_dir: /app
    volumes:
      - "./frontend:/app"
    ports:
      - ${NEXT_PORT}
    tty: true
    env_file:
      - .env
    environment:
      - WATCHPACK_POLLING=true
    command: ${NEXT_CMD}